### ISSUE TITLE
Can't build with ghc-9.0.1

### ISSUE THREAD

**Issue by l29ah** [mokus0/th-extras#7]
```
[1 of 1] Compiling Language.Haskell.TH.Extras ( src/Language/Haskell/TH/Extras.hs, /tmp/th-extras/dist-newstyle/build/x86_64-linux/ghc-9.0.1/th-extras-0.0.0.4/build/Language/Haskell/TH/Extras.o, /tmp/th-extras/dist-newstyle/build/x86_64-linux/ghc-9.0.1/th-extras-0.0.0.4/build/Language/Haskell/TH/Extras.dyn_o )

src/Language/Haskell/TH/Extras.hs:49:17: error:
    • Expecting one more argument to ‘TyVarBndr’
      Expected a type, but ‘TyVarBndr’ has kind ‘* -> *’
    • In the type signature: nameOfBinder :: TyVarBndr -> Name
   |
49 | nameOfBinder :: TyVarBndr -> Name
   |                 ^^^^^^^^^

src/Language/Haskell/TH/Extras.hs:58:27: error:
    • Expecting one more argument to ‘TyVarBndr’
      Expected a type, but ‘TyVarBndr’ has kind ‘* -> *’
    • In the type signature: varsBoundInCon :: Con -> [TyVarBndr]
   |
58 | varsBoundInCon :: Con -> [TyVarBndr]
   |                           ^^^^^^^^^

src/Language/Haskell/TH/Extras.hs:254:28: error:
    • Expecting one more argument to ‘TyVarBndr’
      Expected a type, but ‘TyVarBndr’ has kind ‘* -> *’
    • In the first argument of ‘Q’, namely ‘([TyVarBndr], Int)’
      In the type signature: tyConArity' :: Name -> Q ([TyVarBndr], Int)
    |
254 | tyConArity' :: Name -> Q ([TyVarBndr], Int)
    |                            ^^^^^^^^^
```
